name: QGIS tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-qgis-ltr:
    runs-on: ubuntu-latest
    container:
      image: qgis/qgis:ltr
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install test dependencies
        run: pip install pytest --break-system-packages

      - name: Run tests
        working-directory: qgis
        env:
          PYTHONPATH: .
        run: xvfb-run -a pytest -v tests/test_algorithm.py