name: QGIS CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-qgis-ltr:
    name: QGIS LTR Tests
    runs-on: ubuntu-latest
    container:
      image: qgis/qgis:ltr
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install sbanks_core
        run: pip install ./qgis/sbanks/vendor/sbanks-lib --break-system-packages

      - name: Install test dependencies
        run: pip install pytest --break-system-packages

      - name: Run tests
        working-directory: qgis
        env:
          PYTHONPATH: .
        run: xvfb-run -a pytest -v tests/test_algorithm.py